import type { Ansatt } from "@/lib/domain";

export const IMPORTERTE_ANSATTE: Ansatt[] = [
  {
    "id": "imp-amund",
    "fornavn": "Amund",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-andre",
    "fornavn": "Andre",
    "etternavn": "ø",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-andre",
    "fornavn": "Andre",
    "etternavn": "Ø",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-andre",
    "fornavn": "André",
    "etternavn": "Ø",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-andre",
    "fornavn": "Andrè",
    "etternavn": "Ø",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-andrejs",
    "fornavn": "Andrejs",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-andresj",
    "fornavn": "Andresj",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-andrius",
    "fornavn": "Andrius",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-anstein",
    "fornavn": "Anstein",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-arnt-georg",
    "fornavn": "Arnt",
    "etternavn": "Georg",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-arnt-georg-2s",
    "fornavn": "Arnt",
    "etternavn": "Georg 2s",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-arnt-georg-2s",
    "fornavn": "Arnt",
    "etternavn": "Georg, 2s",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-arturs",
    "fornavn": "Arturs",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-audun",
    "fornavn": "Audun",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-audun-e",
    "fornavn": "Audun",
    "etternavn": "E",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-bakshi",
    "fornavn": "Bakshi",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-baksi",
    "fornavn": "Baksi",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-cato",
    "fornavn": "Cato",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-chien",
    "fornavn": "Chien",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-christian-2s",
    "fornavn": "Christian",
    "etternavn": "2s",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-christian-e",
    "fornavn": "Christian",
    "etternavn": "E",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-dawid",
    "fornavn": "Dawid",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-dawid-b",
    "fornavn": "Dawid",
    "etternavn": "B",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-erik",
    "fornavn": "erik",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-erik",
    "fornavn": "Erik",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-erik-s",
    "fornavn": "Erik",
    "etternavn": "s",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-frode",
    "fornavn": "Frode",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-frode",
    "fornavn": "Frode",
    "etternavn": "Ø",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-gdf",
    "fornavn": "Gdf",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-gdf",
    "fornavn": "GDF",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-gjermund",
    "fornavn": "Gjermund",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-hilafu",
    "fornavn": "Hilafu",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-hakon",
    "fornavn": "Håkon",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-hakon-a",
    "fornavn": "Håkon",
    "etternavn": "A",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-ivan-d",
    "fornavn": "Ivan",
    "etternavn": "D",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-ivan-j",
    "fornavn": "Ivan",
    "etternavn": "J",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-iver",
    "fornavn": "Iver",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-jack",
    "fornavn": "Jack",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-jack-2skift",
    "fornavn": "Jack",
    "etternavn": "2skift",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-jack-2-skift",
    "fornavn": "Jack,",
    "etternavn": "2 skift",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-john-o",
    "fornavn": "John",
    "etternavn": "o",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-john-o",
    "fornavn": "John",
    "etternavn": "O",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-john-olav",
    "fornavn": "John",
    "etternavn": "Olav",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-josse",
    "fornavn": "Josse",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-juri",
    "fornavn": "Juri",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-jurij",
    "fornavn": "Jurij",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-j-rn",
    "fornavn": "jørn",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-j-rn",
    "fornavn": "Jørn",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-j-rn-s",
    "fornavn": "Jørn",
    "etternavn": "S",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-lundstad",
    "fornavn": "Lundstad",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-madelen",
    "fornavn": "Madelen",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-mateus",
    "fornavn": "Mateus",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-mats",
    "fornavn": "Mats",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-morten",
    "fornavn": "Morten",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-morten-b",
    "fornavn": "Morten",
    "etternavn": "B",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-morten-s",
    "fornavn": "Morten",
    "etternavn": "s",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-morten-s",
    "fornavn": "Morten",
    "etternavn": "S",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-olav",
    "fornavn": "Olav",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-ottar",
    "fornavn": "Ottar",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-pelle",
    "fornavn": "Pelle",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-perti",
    "fornavn": "perti",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-perti",
    "fornavn": "Perti",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-pal",
    "fornavn": "Pål",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-pal-w",
    "fornavn": "Pål",
    "etternavn": "w",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-pal-w",
    "fornavn": "Pål",
    "etternavn": "W",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-reza",
    "fornavn": "Reza",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-roger",
    "fornavn": "roger",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-roger",
    "fornavn": "Roger",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-roger-m",
    "fornavn": "Roger",
    "etternavn": "m",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-roger-m",
    "fornavn": "Roger",
    "etternavn": "M",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-roger-m",
    "fornavn": "roger",
    "etternavn": "m",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-roger-m",
    "fornavn": "Roger",
    "etternavn": "m",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-roger-m",
    "fornavn": "Roger",
    "etternavn": "M",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-roger-s",
    "fornavn": "Roger",
    "etternavn": "S",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-ronny-s",
    "fornavn": "ronny",
    "etternavn": "s",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-ronny-s",
    "fornavn": "Ronny",
    "etternavn": "s",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-rufad",
    "fornavn": "Rufad",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-ruffad",
    "fornavn": "Ruffad",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-rune-b",
    "fornavn": "Rune",
    "etternavn": "B",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-rune-be",
    "fornavn": "Rune",
    "etternavn": "Be",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-stein-a",
    "fornavn": "Stein",
    "etternavn": "A",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-stein-arve",
    "fornavn": "Stein",
    "etternavn": "Arve",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-stian",
    "fornavn": "Stian",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-thomas",
    "fornavn": "Thomas",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-thomas",
    "fornavn": "Thomas",
    "etternavn": "Ø",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-thorbj-rn",
    "fornavn": "Thorbjørn",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-tommy",
    "fornavn": "Tommy",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-tore",
    "fornavn": "Tore",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-trond-h",
    "fornavn": "Trond",
    "etternavn": "H",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-v-d",
    "fornavn": "V-D",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-vd-rute",
    "fornavn": "VD",
    "etternavn": "RUTE",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-vebj-rn",
    "fornavn": "Vebjørn",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-ivind",
    "fornavn": "Øivind",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-ivind-2s",
    "fornavn": "Øivind",
    "etternavn": "2s",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  },
  {
    "id": "imp-yvind",
    "fornavn": "Øyvind",
    "etternavn": "",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Excel"
  }
];
