import type { Ansatt } from "@/lib/domain";

/** Ansatte importert fra Bemanning 2026.xlsx (113 personer). */
export const IMPORTERTE_ANSATTE_BEMANNING_2026: Ansatt[] = [
  {
    "id": "a-barberi-abbas",
    "fornavn": "Barberi",
    "etternavn": "Abbas",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-khaled-mohamed-abdi",
    "fornavn": "Khaled Mohamed",
    "etternavn": "Abdi",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-hakon-amb",
    "fornavn": "Håkon",
    "etternavn": "Amb",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-jamshid-amirshah",
    "fornavn": "Jamshid",
    "etternavn": "Amirshah",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-amund-nygaard-andersen",
    "fornavn": "Amund Nygaard",
    "etternavn": "Andersen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-olav-andreassen",
    "fornavn": "Olav",
    "etternavn": "Andreassen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-mohammad-bakhshi",
    "fornavn": "Mohammad",
    "etternavn": "Bakhshi",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-morten-bakken",
    "fornavn": "Morten",
    "etternavn": "Bakken",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-geza-balint",
    "fornavn": "Geza",
    "etternavn": "Balint",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-arturs-bambrovskis",
    "fornavn": "Arturs",
    "etternavn": "Bambrovskis",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-david-baranowski",
    "fornavn": "David",
    "etternavn": "Baranowski",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-rune-berntsen",
    "fornavn": "Rune",
    "etternavn": "Berntsen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-rune-bjerklund",
    "fornavn": "Rune",
    "etternavn": "Bjerklund",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-marcus-blomberg",
    "fornavn": "Marcus",
    "etternavn": "Blomberg",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-cien-van-cao",
    "fornavn": "Cien Van",
    "etternavn": "Cao",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-jurij-ciuikov",
    "fornavn": "Jurij",
    "etternavn": "Ciuikov",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-arturs-dambrovskis",
    "fornavn": "Arturs",
    "etternavn": "Dambrovskis",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-ivan-djordjevic",
    "fornavn": "Ivan",
    "etternavn": "Djordjevic",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-christian-elvestad",
    "fornavn": "Christian",
    "etternavn": "Elvestad",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-morten-engebakken",
    "fornavn": "Morten",
    "etternavn": "Engebakken",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-audun-esbj-rnsen",
    "fornavn": "Audun",
    "etternavn": "Esbjørnsen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-vidar-frislie",
    "fornavn": "Vidar",
    "etternavn": "Frislie",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-tore-furuli",
    "fornavn": "Tore",
    "etternavn": "Furuli",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-soren-fust",
    "fornavn": "Sören",
    "etternavn": "Fust",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx · 0526 · Excel: Sören Fust (0526)"
  },
  {
    "id": "a-r-stum-arnt-georg",
    "fornavn": "Røstum Arnt",
    "etternavn": "Georg",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-lars-reidar-gj-rslie",
    "fornavn": "Lars Reidar",
    "etternavn": "Gjørslie",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-roy-atle-hagen",
    "fornavn": "Roy Atle",
    "etternavn": "Hagen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-trond-hagen",
    "fornavn": "Trond",
    "etternavn": "Hagen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-yvind-hagen",
    "fornavn": "Øyvind",
    "etternavn": "Hagen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-fredrik-hirvioja",
    "fornavn": "Fredrik",
    "etternavn": "Hirvioja",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-paul-ivar-holden",
    "fornavn": "Paul Ivar",
    "etternavn": "Holden",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-roald-holsten",
    "fornavn": "Roald",
    "etternavn": "Holsten",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-kristian-holtet",
    "fornavn": "Kristian",
    "etternavn": "Holtet",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-simon-huhtimo",
    "fornavn": "Simon",
    "etternavn": "Huhtimo",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-andre-normann-h-galmen",
    "fornavn": "Andre Normann",
    "etternavn": "Høgalmen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-joakim-haklev",
    "fornavn": "Joakim",
    "etternavn": "Håklev",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-andreas-haave",
    "fornavn": "Andreas",
    "etternavn": "Haave",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-tommy-iversen",
    "fornavn": "Tommy",
    "etternavn": "Iversen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-frode-jansen",
    "fornavn": "Frode",
    "etternavn": "Jansen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-tor-inge-jansen",
    "fornavn": "Tor Inge",
    "etternavn": "Jansen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-john-jevne",
    "fornavn": "John",
    "etternavn": "Jevne",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-ivan-morgan-johansen",
    "fornavn": "Ivan Morgan",
    "etternavn": "Johansen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-tobias-mellum-johansen",
    "fornavn": "Tobias Mellum",
    "etternavn": "Johansen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-john-arne-johnsen",
    "fornavn": "John Arne",
    "etternavn": "Johnsen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-berg-jonas",
    "fornavn": "Berg",
    "etternavn": "Jonas",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-johan-kartomten",
    "fornavn": "Johan",
    "etternavn": "Kartomten",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-thorbj-rn-kjernaas",
    "fornavn": "Thorbjørn",
    "etternavn": "Kjernaas",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-per-robert-kristiansen",
    "fornavn": "Per Robert",
    "etternavn": "Kristiansen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-rune-l-kke-kristiansen",
    "fornavn": "Rune Løkke",
    "etternavn": "Kristiansen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-karl-erik-kristmoen",
    "fornavn": "Karl Erik",
    "etternavn": "Kristmoen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-nils-kroken",
    "fornavn": "Nils",
    "etternavn": "Kroken",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-leiv-trygve-langseth",
    "fornavn": "Leiv Trygve",
    "etternavn": "Langseth",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-alexander-lindstrom",
    "fornavn": "Alexander",
    "etternavn": "Lindström",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx · 0209 · Excel: Alexander Lindström (0209)"
  },
  {
    "id": "a-stein-arve-lunde",
    "fornavn": "Stein Arve",
    "etternavn": "Lunde",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-per-ola-ake-lundgren",
    "fornavn": "Per Ola Åke",
    "etternavn": "Lundgren",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-john-olav-lundstad",
    "fornavn": "John Olav",
    "etternavn": "Lundstad",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-bj-rn-luvasen",
    "fornavn": "Bjørn",
    "etternavn": "Luvåsen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-ottar-luvasen",
    "fornavn": "Ottar",
    "etternavn": "Luvåsen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-wilson-martin",
    "fornavn": "Wilson",
    "etternavn": "Martin",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-thor-olav-mellum",
    "fornavn": "Thor Olav",
    "etternavn": "Mellum",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-hilafu-mentay",
    "fornavn": "Hilafu",
    "etternavn": "Mentay",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-roger-moseng",
    "fornavn": "Roger",
    "etternavn": "Moseng",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-cato-nilsen",
    "fornavn": "Cato",
    "etternavn": "Nilsen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-andreas-nilsson",
    "fornavn": "Andreas",
    "etternavn": "Nilsson",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-mans-olofsson",
    "fornavn": "Måns",
    "etternavn": "Olofsson",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx · 0209 · Excel: Måns Olofsson (0209)"
  },
  {
    "id": "a-stian-otnes",
    "fornavn": "Stian",
    "etternavn": "Otnes",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-nikolaos-pastalatzis",
    "fornavn": "Nikolaos",
    "etternavn": "Pastalatzis",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-linas-pauliukevicius",
    "fornavn": "Linas",
    "etternavn": "Pauliukevicius",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-engeskaug-peder",
    "fornavn": "Engeskaug",
    "etternavn": "Peder",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-jack-petersen",
    "fornavn": "Jack",
    "etternavn": "Petersen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-gjermund-petrud",
    "fornavn": "Gjermund",
    "etternavn": "Petrud",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-perti-portimo",
    "fornavn": "Perti",
    "etternavn": "Portimo",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-thorsen-pal",
    "fornavn": "Thorsen.",
    "etternavn": "Pål",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-gyorgy-rezmanyi",
    "fornavn": "Gyorgy",
    "etternavn": "Rezmanyi",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-mateus-rogstad",
    "fornavn": "Mateus",
    "etternavn": "Rogstad",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-s-rbye-ronny",
    "fornavn": "Sørbye",
    "etternavn": "Ronny",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-ferad-mehmed-rufad",
    "fornavn": "Ferad Mehmed",
    "etternavn": "Rufad",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-andrius-rukas",
    "fornavn": "Andrius",
    "etternavn": "Rukas",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-haris-sabic",
    "fornavn": "Haris",
    "etternavn": "Sabic",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-reza-sakhicade",
    "fornavn": "Reza",
    "etternavn": "Sakhicade",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-j-rn-erik-sanaker",
    "fornavn": "Jørn Erik",
    "etternavn": "Sanaker",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-frode-sandmoen",
    "fornavn": "Frode",
    "etternavn": "Sandmoen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-andrejs-seleznovs",
    "fornavn": "Andrejs",
    "etternavn": "Seleznovs",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-anstein-skj-nsberg",
    "fornavn": "Anstein",
    "etternavn": "Skjønsberg",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-roger-skogheim",
    "fornavn": "Roger",
    "etternavn": "Skogheim",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-roger-haug-skogheim",
    "fornavn": "Roger Haug",
    "etternavn": "Skogheim",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-thomas-skybakmoen",
    "fornavn": "Thomas",
    "etternavn": "Skybakmoen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-madelen-asen-slaen",
    "fornavn": "Madelen Åsen",
    "etternavn": "Slåen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-erik-solbakken",
    "fornavn": "Erik",
    "etternavn": "Solbakken",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-oleg-sonin",
    "fornavn": "Oleg",
    "etternavn": "Sonin",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-morten-steinbakken",
    "fornavn": "Morten",
    "etternavn": "Steinbakken",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-kai-viggo-stenersen",
    "fornavn": "Kai Viggo",
    "etternavn": "Stenersen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-anders-storsveen",
    "fornavn": "Anders",
    "etternavn": "Storsveen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-silje-sveen",
    "fornavn": "Silje",
    "etternavn": "Sveen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-geir-svendsen",
    "fornavn": "Geir",
    "etternavn": "Svendsen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-vebj-rn-sveum",
    "fornavn": "Vebjørn",
    "etternavn": "Sveum",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-stein-s-rmoen",
    "fornavn": "Stein",
    "etternavn": "Sørmoen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-samson-tekeste",
    "fornavn": "Samson",
    "etternavn": "Tekeste",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-jan-viggo-thorsen",
    "fornavn": "Jan Viggo",
    "etternavn": "Thorsen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-nyhus-tore",
    "fornavn": "Nyhus",
    "etternavn": "Tore",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-iver-tr-nnes",
    "fornavn": "Iver",
    "etternavn": "Trønnes",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-thorvald-vang",
    "fornavn": "Thorvald",
    "etternavn": "Vang",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx · reserve uke 9-14 · Excel: Vang, Thorvald (reserve uke 9-14)"
  },
  {
    "id": "a-torgeir-vestli",
    "fornavn": "Torgeir",
    "etternavn": "Vestli",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-mohamed-ahmed-weheliye",
    "fornavn": "Mohamed Ahmed",
    "etternavn": "Weheliye",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-per-westbye",
    "fornavn": "Per",
    "etternavn": "Westbye",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx · 0526 · Excel: Per Westbye (0526)"
  },
  {
    "id": "a-pal-westerhaug",
    "fornavn": "Pål",
    "etternavn": "Westerhaug",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-malec-wojtek",
    "fornavn": "Malec",
    "etternavn": "Wojtek",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-oliver-zuljevic",
    "fornavn": "Oliver",
    "etternavn": "Zuljevic",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-frode-degardstuen",
    "fornavn": "Frode",
    "etternavn": "Ødegårdstuen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-andre-stli",
    "fornavn": "Andre",
    "etternavn": "Østli",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-daniel-verby",
    "fornavn": "Daniel",
    "etternavn": "Øverby",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-thomas-yen",
    "fornavn": "Thomas",
    "etternavn": "Øyen",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  },
  {
    "id": "a-mats-astr-m",
    "fornavn": "Mats",
    "etternavn": "Åstrøm",
    "telefon": "",
    "epost": "",
    "rolle": "Sjåfør",
    "avdeling": "",
    "selskap": "Asko",
    "stillingsprosent": 100,
    "kompetanse": [],
    "førerkort": [],
    "aktiv": true,
    "kommentar": "Importert fra Bemanning 2026.xlsx"
  }
];
